# Generated by Django 2.1 on 2020-08-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200823_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Camisa'), ('SW', 'Camiseta'), ('OW', 'Otra prenda')], default='S', max_length=3),
        ),
    ]
